### PR TITLE
Fix constant-time behaviour for ct_reduce/ct_div_rem

### LINKED ISSUE #116: `UInt::{ct_div_rem, ct_reduce}` are not constant-time
As noted in #115, both of these functions compute values and then pass them as the `rhs` to `UInt::shl_vartime`.

- https://github.com/RustCrypto/crypto-bigint/blob/ed8d96b/src/uint/div.rs#L24
- https://github.com/RustCrypto/crypto-bigint/blob/ed8d96b/src/uint/div.rs#L63

cc @andrewwhitehead @mikelodder7

### PR DESCRIPTION
**Pull request by andrewwhitehead**
Fixes #116

### CODE REVIEW

File: src/uint/div.rs [hunk 1]
```diff
@@ -17,35 +17,29 @@ impl<const LIMBS: usize> UInt<LIMBS> {
...
             if bd == 0 {
                 break;
             }
             bd -= 1;
             c = c.shr_vartime(1);
-            e = e.shr_vartime(1);
+            quo = quo.shl_vartime(1);
+        }
+
+        let is_some = if mb == 0 { 0 } else { 1 };
```
Comment (andrewwhitehead) [inline src/uint/div.rs:39]: I believe this is sufficient since there are no constant-time guarantees around `rhs`.

File: src/uint/div.rs [hunk 2]
```diff
@@ -17,35 +17,29 @@ impl<const LIMBS: usize> UInt<LIMBS> {
     /// When used with a fixed `rhs`, this function is constant-time with respect
     /// to `self`.
     pub(crate) const fn ct_div_rem(&self, rhs: &Self) -> (Self, Self, u8) {
-        let mut bd = self.bits().saturating_sub(rhs.bits());
+        let mb = rhs.bits();
+        let mut bd = (LIMBS * Limb::BIT_SIZE) - mb;
         let mut rem = *self;
         let mut quo = Self::ZERO;
-
         let mut c = rhs.shl_vartime(bd);
```
Comment (tarcieri) [inline src/uint/div.rs:24]: Doesn't this still shift by a variable number of bits?

Comment (andrewwhitehead) [reply src/uint/div.rs:24]: It depends only on the value of `rhs`, so it should be constant for a given divisor. Previously it depended on the value of `self` as well.

Comment (tarcieri) [reply src/uint/div.rs:24]: Aha!

File: src/uint/div.rs (hunk 1 above)
Comment (mikelodder7) [inline src/uint/div.rs:39]:
```suggestion
        let is_some = ((mb | -mb) >> 63) + 1;
```

Comment (mikelodder7) [reply src/uint/div.rs:39]: Or

```suggestion
        let is_some = Limb::is_zero(mb);
```

Comment (tarcieri) [reply src/uint/div.rs:39]: Might be good to leave a comment to that effect

Comment (tarcieri) [reply src/uint/div.rs:39]: Wouldn't `63` need to be `(Limb::BIT_SIZE - 1)`?

This seems ok but I'm also ok with a branch on a value computed from `rhs` where we already assume timing is variable in respect to its value

Comment (andrewwhitehead) [reply src/uint/div.rs]: I threw in a `ct_select` since it doesn't make a significant difference to the runtime.

Comment (mikelodder7) [reply src/uint/div.rs]: Can you add your test case that triggered this PR?

Comment (mikelodder7) [reply src/uint/div.rs]: Want to make sure it’s actually fixed

Comment (tarcieri) [reply src/uint/div.rs]: Just saw this comment.

Perhaps it would make sense to use something like [`sidefuzz`](https://github.com/phayes/sidefuzz) to test constant-time behvaior?

Comment (andrewwhitehead) [reply src/uint/div.rs]: My test was a criterion benchmark, I suspected it from reading the code.

```rs
#[macro_use]
extern crate criterion;
use criterion::{black_box, Criterion};
fn criterion_benchmark(c: &mut Criterion) {
    use crypto_bigint::U256;
    let u1 = U256::from_be_hex("0123456780123456780123456780123456780123456780123456780123456780");
    let u2 = U256::from_be_hex("0000000000000000000000000000000000000000000000000000000000000012");
    let md = U256::from_be_hex("0000000000000000000000000000000000000000000000000000000012345678");
    c.bench_function("reduce large", move |b| {
        b.iter(|| black_box(u1).reduce(&md))
    });
    c.bench_function("reduce small", move |b| {
        b.iter(|| black_box(u2).reduce(&md))
    });
}
criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```

Old timing:

```
reduce large            time:   [948.59 ns 949.00 ns 949.46 ns]                           
Found 8 outliers among 100 measurements (8.00%)
  6 (6.00%) high mild
  2 (2.00%) high severe

reduce small            time:   [15.520 ns 15.535 ns 15.549 ns]                           
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) low mild
  2 (2.00%) high severe
```

And patched:

```
reduce large            time:   [955.12 ns 955.84 ns 956.81 ns]                          
Found 10 outliers among 100 measurements (10.00%)
  3 (3.00%) high mild
  7 (7.00%) high severe

reduce small            time:   [955.58 ns 956.55 ns 957.99 ns]                          
Found 11 outliers among 100 measurements (11.00%)
  4 (4.00%) high mild
  7 (7.00%) high severe
```

Comment (andrewwhitehead) [reply src/uint/div.rs]: Also if somebody feels like implementing a limb-based method this looks interesting: https://www.bearssl.org/bigint.html#modred
